sudo: required
language: generic
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: LJtjU5DJmNSsknCMwUgD7gofmMKWAjUgPhrk204tWq7oHZkZEztw7VIp77u6rtTXLbZfFYUIf6LoB1exYPIHpbpLnWohLdrHSfHp4S41Sf7Ag5CQmKE+YfMlmQgzDsSFZ4ezFIWQqpt1tkFS4f+Xy1Xp94yJDNaJ6G1hIBgCfy4+GbIoZDFDDY7iOkt+YTzw55YRnPFFH/rXpHtMQpt0Vw4FVTHdcnOxCl2jGAV0GxJNmxwLZBBYxy0ak9b+2MoEnu6AX7xJl2NnxLhYiXSWn9LaePDGwP2FPCdPEHwaLV6CRd8H8cm41QzN95KLvLFzfYCz1DPybRwD0NC9x/CQ/NTu28iSbvI96pYHNwFj99ANen+AMwUuDOSKhLpNKxBUu1oZdXZR1Ls4W0LH6VMlydRekw0163YI5uF3Or9eWXW7CIlLA+iRuT9tdmfGtgqhVE0Z9kJ/bfUcrujqKp9q2ax54uW/geicwSQ/PwkJFQD0lBUeW4Mh7mLz44F+4FOodP/UNIyp0fOsXYk/pSOptc5y/Kzq6wWRiVfH4dMvcMPkM2QLiR9KKPE/LVTVKFY38BRKJH+umGO9bnXjAdrXe0dfBOZ6Fl4ggFsUm/zavwBL9hpUsIh3xQNYC20f0gh3zhra7RAxwWPeO40YhZCWJIy8mj0x/236m4fOP0df3VM=
  - secure: CnNLkrO3JyBh8O33b4JiNVaQTlo6vfTOWcfspVmLibYaMQek/3US1Ey9W9UB/y8Gz3QfSsCyZTWhM3fmOKkVfqQgO6EfVD2nuYuC6FoBdolKvKDDcQZzsHi74t/6qRqKJZ5gp0cc5IXAH6BoM2ZXdej6/4rGwVidLTELat75wMLweAON6+TCAySe60YudpXVOta3uxZJrvvOc5qRBw+/nqSnPeSgBnZ8MwzFM9QFDeUe2oSmExogLNRNs4zygAhTXTEJMLNuyH1Pl/4cDum5ebxf7CHr1yeYycXI+ZoRPH1P43X0m8uGobNzj7KazaXEJryfxbSp+wTKmxpcBy/k0WTVh/+Fwz/Wq+rwt5eODpCwFsP1q6h9XJ8wqY4eiZfzKkbd+zGV78XQVOEBqRi1HbvpzXB0bMWOJHzT+B1H7uq/hWIPIzbgImf7ZTVed1RVZ3EG0PFtwrd5WPVdI/fHg0eboN4g8xksPye6RBn5TE1JblLDkM4M4R0eXexPFSNvvsEpR7FjXTXCZ3LIYLDP1CZex6Fgn+priPlCFPw5iaR4Vgf3cc/A0cqFG1iuh83tSU0eoqYo6NIaxH+IcU4t+qcmr+sQD5PLL9eixyVUe47OyRyULRes3jYSvKkCFxXVdRVeHQh/RK+eVS04+hbojuW+tLymFc9bewzUaUSGoVk=
  - secure: oVvjx8m9rTrpdcS6dcsy0sEg1rW4d5BZJXB7FCgTOQr44IWBxAVQgCEVeZVQ2Y6fD0+T4TmeNcO7yjpEsf7R9hZCG597Wohl75MQNaa+1vjWMJl6FVkvOWriBP1b2btzmqGWf8Mbi9aueZnYTKhUBWZO61l+LGs9uK58grVOsnr/drNVClwZo+Oh6oVN3reNO43nkPI01briA7wukrrQhQEuApdpHEdvtTl0wuDo8HaeB7Kl4H+9X3QcW17onGxXGzLyGRr92BKZle+Qrg/48OgYETXp5JuwQMdvfG3Y0Q+u3CFwBo5k6PoAEavcYaDcZmpgiTYPf+RcvILQDJLVEVFdegN7dpZdUQ4HmvMLhAN73Fn0uJI8qx9SDa+Ld37tTBH7Hy3IMdMH5qArFogohAFDUBJ45xhnCVOKNVra4vWCrMJR7ezOIAccuInel332ni3dittydYEa98iPPdhG1AXefzdrpUi6OXzVrUpWOZV6h2IGNtw/LLS+WiAciagir9hqw60WlnCofDNYMplgHOMSLaW9BIOrbnkw9YCkqHvPr+NfmZYg/Dbd5SUwWfEIFmSYlVKljSS30RYHlYCWQ4n/lvk0506a6zitZLYrgvyLfHnXioaHxr+5XBGTMLBkMlqx5VUtW2kpeU0LlVAVdju65v6HjiukCJQVeSIFhM8=
script:
- travis_wait 120 docker build -t brookskd/docker-ethminer:$COMMIT .
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=brookskd/docker-ethminer
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
- docker logout
